import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Homenagem</title>
        
        <link rel="icon" type="image/x-icon" href="/image/logo-homenagem-rosa.png"></link>

        <link rel="stylesheet" href="/css/style.css" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet"/>
      </head>
      
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          {/* Aqui você pode adicionar seu conteúdo de cabeçalho, se necessário */}
        </header>
        {children}
      </body>
    </html>
  );
}
